### ISSUE TITLE
tour: var declaration in for initializer

### ISSUE THREAD

**Issue by imaizume** [atotto/go-tour-jp#28]
Context: https://go-tour-jp.appspot.com/flowcontrol/1

![go-tour-jp appspot com_flowcontrol_1](https://user-images.githubusercontent.com/16273903/48977395-b716db80-f0dc-11e8-8512-53b77baaf6f1.png)

## About

The content of the page of "for statement" is still written by deprecated
 syntax and you'll encounter an error as follows:
`prog.go:7:10: syntax error: var declaration not allowed in for initializer`

It's helpful for beginner to update the sample code. 

### [Japanese](https://go-tour-jp.appspot.com/flowcontrol/1)

```go
package main

import "fmt"

func main() {
	sum := 0
	for var i int = 0; i < 10; i++ {
		sum += i
	}
	fmt.Println(sum)
}
```

### [English](https://tour.golang.org/flowcontrol/1)

```go
package main

import "fmt"

func main() {
	sum := 0
	for i := 0; i < 10; i++ {
		sum += i
	}
	fmt.Println(sum)
}
```

**Comment by atotto** [comment]
Resolved. Thank you!
