### ISSUE TITLE
go-tour-jp.appspot.com が閲覧不可状態

### ISSUE THREAD

**Issue by secondarykey** [atotto/go-tour-jp#42]
「Go 1.9 is no longer available.」と出てますので、
GoogleAppEngine 2nd Generation 対応が行われてない為かと思います。
対応等の予定はございますでしょうか？

**Comment by atotto** [comment]
ご連絡ありがとうございます。
修正いたしました！

**Comment by secondarykey** [comment]
お盆な中、迅速な対応ありがとうございます！
